In [48]:
import pandas as pd
import numpy as np
import hashlib

df = pd.read_csv("masking_dataset_1000.csv")

In [49]:
df

             Name       Phone                       Email  Salary
0     Pooja Verma  9986331670     poojaverma176@yahoo.com  125139
1      Neha Yadav  9157655564    nehayadav523@outlook.com  142849
2      Amit Singh  9152120463       amitsingh73@yahoo.com  129673
3     Rohit Patel  9749454434     rohitpatel890@gmail.com   87540
4      Amit Joshi  9801169075    amitjoshi869@outlook.com   49767
..            ...         ...                         ...     ...
995    Amit Yadav  9416261615       amityadav50@gmail.com  142743
996   Rohit Desai  9377323780   rohitdesai969@outlook.com  126905
997  Anjali Mehta  9713737173  anjalimehta884@outlook.com   92941
998   Vikas Mehta  9691729529     vikasmehta140@gmail.com   66621
999    Amit Desai  9182645598      amitdesai690@yahoo.com  139154

[1000 rows x 4 columns]

In [50]:
def mask_name(name):
    return name[0]+"****"

In [51]:
def mask_phone(phone):
    phone = str(phone)
    return "XXXXXX" + phone[-4:]

In [52]:
def mask_email(email):
    username, domain = email.split("@")
    return username[0] + "***@" + domain

In [53]:
import random

def mask_salary(salary_list):
    random.shuffle(salary_list)
    return salary_list

In [54]:
masked_df = df.copy()

In [55]:
masked_df["Email"] = df["Email"].apply(mask_email)
masked_df["Phone"] = df["Phone"].apply(mask_phone)
masked_df["Name"] = df["Name"].apply(mask_name)

# Salary needs list
masked_df["Salary"] = mask_salary(df["Salary"].tolist())

In [61]:
print(df)
print(masked_df)

             Name       Phone                       Email  Salary
0     Pooja Verma  9986331670     poojaverma176@yahoo.com  125139
1      Neha Yadav  9157655564    nehayadav523@outlook.com  142849
2      Amit Singh  9152120463       amitsingh73@yahoo.com  129673
3     Rohit Patel  9749454434     rohitpatel890@gmail.com   87540
4      Amit Joshi  9801169075    amitjoshi869@outlook.com   49767
..            ...         ...                         ...     ...
995    Amit Yadav  9416261615       amityadav50@gmail.com  142743
996   Rohit Desai  9377323780   rohitdesai969@outlook.com  126905
997  Anjali Mehta  9713737173  anjalimehta884@outlook.com   92941
998   Vikas Mehta  9691729529     vikasmehta140@gmail.com   66621
999    Amit Desai  9182645598      amitdesai690@yahoo.com  139154

[1000 rows x 4 columns]
      Name       Phone             Email  Salary
0    P****  XXXXXX1670    p***@yahoo.com  109399
1    N****  XXXXXX5564  n***@outlook.com   99395
2    A****  XXXXXX0463    a***@yahoo.com   49317
3    R****  XXXXXX4434    r***@gmail.com  132565
4    A****  XXXXXX9075  a***@outlook.com   95633
..     ...         ...               ...     ...
995  A****  XXXXXX1615    a***@gmail.com  119334
996  R****  XXXXXX3780  r***@outlook.com  108158
997  A****  XXXXXX7173  a***@outlook.com   51678
998  V****  XXXXXX9529    v***@gmail.com   97352
999  A****  XXXXXX5598    a***@yahoo.com   35576

[1000 rows x 4 columns]

In [63]:
masked_df.to_csv('making.csv',index=False)

df

In [62]:
masked_df

      Name       Phone             Email  Salary
0    P****  XXXXXX1670    p***@yahoo.com  109399
1    N****  XXXXXX5564  n***@outlook.com   99395
2    A****  XXXXXX0463    a***@yahoo.com   49317
3    R****  XXXXXX4434    r***@gmail.com  132565
4    A****  XXXXXX9075  a***@outlook.com   95633
..     ...         ...               ...     ...
995  A****  XXXXXX1615    a***@gmail.com  119334
996  R****  XXXXXX3780  r***@outlook.com  108158
997  A****  XXXXXX7173  a***@outlook.com   51678
998  V****  XXXXXX9529    v***@gmail.com   97352
999  A****  XXXXXX5598    a***@yahoo.com   35576

[1000 rows x 4 columns]