### Assignment No. 9

#### Name : Shreyas Babar
#### Roll no. : EN23107002
#### Class : AI(A)-C

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "Name": ["Amit Sharma", "Neha Patil", "Rahul Verma", "Sneha Kulkarni"],
    "Email": ["amit@gmail.com", "neha@gmail.com", "rahul@gmail.com", "sneha@gmail.com"],
    "Phone": ["9876543210", "9123456780", "9988776655", "9871234567"],
    "Salary": [50000, 65000, 72000, 58000]
}

df = pd.DataFrame(data)

print("Original Dataset")
df

Original Dataset

             Name            Email       Phone  Salary
0     Amit Sharma   amit@gmail.com  9876543210   50000
1      Neha Patil   neha@gmail.com  9123456780   65000
2     Rahul Verma  rahul@gmail.com  9988776655   72000
3  Sneha Kulkarni  sneha@gmail.com  9871234567   58000

In [ ]:
sensitive_columns = ["Name", "Email", "Phone", "Salary"]

print("Sensitive Columns:")
print(sensitive_columns)

Sensitive Columns:
['Name', 'Email', 'Phone', 'Salary']

#### Mask Name

In [ ]:
def mask_name(name):
    return name[0] + "***"

#### Mask Email

In [ ]:
def mask_email(email):
    username, domain = email.split("@")
    return username[0] + "***@" + domain

#### Mask Phone

In [ ]:
def mask_phone(phone):
    return "XXXXX" + phone[-4:]

#### Shuffle Salaries

In [ ]:
def shuffle_salary(series):
    return np.random.permutation(series)

#### Apply Data Masking

In [ ]:
masked_df = df.copy()

masked_df["Name"] = masked_df["Name"].apply(mask_name)
masked_df["Email"] = masked_df["Email"].apply(mask_email)
masked_df["Phone"] = masked_df["Phone"].apply(mask_phone)
masked_df["Salary"] = shuffle_salary(masked_df["Salary"])

In [ ]:
print("Original Data")
display(df)

print("Masked Data")
display(masked_df)

Original Data

             Name            Email       Phone  Salary
0     Amit Sharma   amit@gmail.com  9876543210   50000
1      Neha Patil   neha@gmail.com  9123456780   65000
2     Rahul Verma  rahul@gmail.com  9988776655   72000
3  Sneha Kulkarni  sneha@gmail.com  9871234567   58000

Masked Data

   Name           Email      Phone  Salary
0  A***  a***@gmail.com  XXXXX3210   72000
1  N***  n***@gmail.com  XXXXX6780   58000
2  R***  r***@gmail.com  XXXXX6655   65000
3  S***  s***@gmail.com  XXXXX4567   50000

In [ ]:
masked_df.to_csv("masked_dataset.csv", index=False)

print("Masked dataset saved successfully.")

Masked dataset saved successfully.

In [ ]:
print("Average Salary (Masked Data):")
print(masked_df["Salary"].mean())

print("Salary Statistics:")
print(masked_df["Salary"].describe())

Average Salary (Masked Data):
61250.0
Salary Statistics:
count        4.00000
mean     61250.00000
std       9429.56344
min      50000.00000
25%      56000.00000
50%      61500.00000
75%      66750.00000
max      72000.00000
Name: Salary, dtype: float64